// The full California benefits shelf shown in the UI as "discover" cards. Only CalFresh is
// engine-computed and carries a dollar figure; EVERY card here carries NO dollar amount
// (anti-overclaim, C3). Each card cites why it may apply + a concrete next step.
export const SHELF = [
  { program: "Medi-Cal", need_group: "Health", one_line: "Free or low-cost health coverage for low-income Californians.", why_short: "Household income appears under the Medi-Cal MAGI threshold (~138% FPL for adults).", citation: { source_id: "HHS-FPL-2025", note: "Medi-Cal MAGI adult threshold ~138% FPL" }, next_step: "Apply at coveredca.com or benefitscal.com." },
  { program: "WIC", need_group: "Kids", one_line: "Food, formula, and nutrition support for pregnant people and kids under 5.", why_short: "CalFresh enrollment is adjunctively income-eligible for WIC.", citation: { source_id: "7CFR-273.2j", note: "WIC adjunctive eligibility via SNAP (7 CFR 246.7)" }, next_step: "Call 1-888-942-9675 or apply at myfamily.wic.ca.gov." },
  { program: "CalEITC / Young Child Tax Credit", need_group: "Money", one_line: "Cash-back state tax credits for working families with low income.", why_short: "Low-to-moderate earned income may qualify; YCTC adds more if you have a child under 6.", citation: { source_id: "HHS-FPL-2025", note: "CalEITC earned-income thresholds" }, next_step: "File a CA return free at ftb.ca.gov, even if not otherwise required." },
  { program: "CARE / FERA (utility discount)", need_group: "Utilities", one_line: "20-35% off your gas and electric bill.", why_short: "Household income appears at or below the CARE threshold (~200% FPL).", citation: { source_id: "HHS-FPL-2025", note: "CPUC CARE income threshold ~200% FPL" }, next_step: "Apply through your utility (PG&E / SCE / SDG&E)." },
  { program: "CA LifeLine", need_group: "Utilities", one_line: "Discounted home phone or cell service.", why_short: "CalFresh participation is a qualifying program for LifeLine.", citation: { source_id: "CDSS-ACL-BBCE", note: "LifeLine program-based eligibility" }, next_step: "Apply at californialifeline.com." },
  { program: "Free & Reduced School Meals", need_group: "Kids", one_line: "Free breakfast and lunch at school, no separate application.", why_short: "Children in CalFresh households are directly certified.", citation: { source_id: "CDSS-MPP-63", note: "NSLP direct certification via SNAP" }, next_step: "Your district enrolls you automatically; confirm with the school office." },
  { program: "SUN Bucks (Summer EBT)", need_group: "Kids", one_line: "Grocery money for school-age kids over the summer.", why_short: "School-age children in CalFresh households are auto-enrolled.", citation: { source_id: "CDSS-MPP-63", note: "Summer EBT auto-enrollment via SNAP/NSLP" }, next_step: "Issued automatically each summer to your EBT card." },
  { program: "Prescription cost pathways", need_group: "Health", one_line: "Lower out-of-pocket drug costs (non-clinical matching only).", why_short: "Copay cards, patient assistance programs, and Cost Plus options by coverage type.", citation: { source_id: "CDSS-MPP-63", note: "Non-clinical cost-pathway matching; ask your prescriber before any change" }, next_step: "Ask the assistant for rx cost pathways, or talk to your pharmacist." },
  { program: "Housing vouchers / rental assistance", need_group: "Housing", one_line: "Help paying rent through local housing authorities.", why_short: "Low-income households may qualify for Section 8 / local rental assistance.", citation: { source_id: "HHS-FPL-2025", note: "HUD income limits (area-based)" }, next_step: "Contact your local public housing authority or 211." },
];
